### ISSUE TITLE
Feature Request: Add "Key Differentiators" and/or "Roadmap" sections

### ISSUE THREAD

**Issue by mellery451** [danscratch/ladder#1]
Would be helpful to have a section in each `Ln` document that describes the key ways that role differs from the previous level (L1 excepted) - and a roadmap for getting into this role. To put it simply, I would like the the `Ln+1` document to offer some key advice about how to get from `Ln` to `Ln+1`.

**Comment by danscratch** [comment]
I feel as though the key advice would be to read the next level and "start doing that". Promotions are usually like that - "you're already doing X, so I guess we'll give you the title." Do you have more concrete ideas on what might go into this section?

**Comment by mellery451** [comment]
giving this more thought, I think the `growth` topic covers most of what I'm looking for. thanks.
